require:
  - rubocop-factory_bot
  - rubocop-rspec_rails

plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'vendor/**/*'

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Max: 100
Metrics/PerceivedComplexity:
  Enabled: false
Rails/BulkChangeTable:
  Enabled: false
Rails/FilePath:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/ExampleWording:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NoExpectationExample:
  Enabled: false
