plugins: rubocop-factory_bot
plugins: rubocop-rails
require: rubocop-rspec
require: rubocop-rspec_rails

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Max: 100
Metrics/PerceivedComplexity:
  Enabled: false
Rails/BulkChangeTable:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/ExampleWording:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/SpecFilePathFormat:
  Enabled: false
RSpec/NoExpectationExample:
  Enabled: false
Rails/Delegate:
  Enabled: false
