version: "3.2"

services:
  # service configuration for our dockerized Rails app
  nrdb_api_server:
    restart: unless-stopped
    network_mode: bridge

    networks:
      - null_signal
      - backend

    # use the Dockerfile next to this file
    build: .

    # sources environment variable configuration for our app
    env_file: .env

    # rely on the RAILS_ENV value of the host machine
    environment:
      POSTGRES_PASSWORD: netrunnerdb
      RAILS_ENV: $RAILS_ENV

    # makes the app container aware of the DB container
    links:
      - db

    volumes:
      - .:/var/www/nrdb-api/
      - ../netrunner-cards-json/:/netrunner-cards-json
      - nrdb-api-logs:/var/www/nrdb-api/log

  # service configuration for our database
  db:
    restart: unless-stopped
    network_mode: bridge
    image: postgres:14.5

    networks:
     - backend

    environment:
      POSTGRES_PASSWORD: netrunnerdb

    # persist the database between containers by storing it in a volume
    volumes:
      - nrdb-api-postgres:/var/lib/postgresql/data

networks:
  backend:
  null_signal:
    external: true

volumes:
  nrdb-api-logs:
  nrdb-api-postgres:
